name: money_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  firebase_core: ^3.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  
  expense_repository:
    path: packages/expense_repository
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/person.png
    - assets/images/
